name: Build project and Deploy Android

on: push

jobs:
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - Android # Build an Android .apk standalone app.
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
      - if: matrix.targetPlatform == 'Android'
        uses: jlumbroso/free-disk-space@v1.3.1
      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
      - uses: actions/upload-artifact@v3
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}

  deployToFirebase:
    runs-on: ubuntu-latest
    needs: buildForAllSupportedPlatforms
    steps:
      - name: Download APK artifact
        uses: actions/download-artifact@v4
        with:
          name: Build-Android
      
      - name: Install Firebase CLI
        run: curl -sL https://firebase.tools | bash

      - name: Authenticate firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_CREDENTIALS }}
        run: echo "${FIREBASE_TOKEN}" > firebase_credentials.json

      - name: Upload APK to Firebase App Distribution
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_CREDENTIALS }}
        run: |
          firebase appdistribution:distribute build/Android/*.apk \
            --app 1:253433464496:android:7f0e622da93780e3ea1d75 \
            --token "$(cat firebase_credentials.json)"
            --release-notes "Testing version 1 distribution" --tester-file testers.txt