name: GameCI Template 🎮

on: push

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

jobs:
  buildAndroid:
    name: Test Set up GameCI
    runs-on: ubuntu-latest
    container:
      image: unityci/editor:2022.3.6f1-android-3.1.0

    steps:
      - name: Set up GameCI
        uses: game-ci/unity-builder@v2
        with:
          unityVersion: '2022.3.6f1'
          targetPlatform: Android
          androidAppBundle: false